// On-page content for the 10 tool pages.
//
// These pages previously shipped ~50 words of unique server-rendered text, so
// they could not rank for the queries they target ("step by step math solver",
// "free AI exam marking", …) even though they are the site's most valuable
// pages. This is real, server-rendered copy: how the tool works, how the output
// differs per exam board, a worked example, and FAQs.
//
// Plain text only — it is rendered directly, not through the markdown renderer.

export type ToolContent = {
  slug: string;
  intro: string;
  howItWorks: { step: string; text: string }[];
  boards: string;
  example: { title: string; body: string };
  tips: string[];
  faqs: { q: string; a: string }[];
};

export const TOOL_CONTENT: Record<string, ToolContent> = {
  "explain": {
    slug: "explain",
    intro: "Stuck on homework? Paste the question, or upload a photo of the textbook page or a PDF, and ask the AI to explain any topic the way your syllabus teaches it. You get the explanation at your level, in your exam board's style, plus key points and follow-up questions. Free, no account needed.",
    howItWorks: [
      { step: "Give it the question", text: "Paste the text, or upload a clear photo of the page or a PDF under 3 MB. Photos are resized automatically, so a normal phone picture is fine." },
      { step: "Set your level once", text: "Tell it your country, year group and exam board in onboarding or settings. Every explanation after that is written for that syllabus and that grade." },
      { step: "Pick length and style", text: "Choose Short for a quick check or Long for a full walkthrough, and switch the format between bullets, paragraphs and step-by-step." },
      { step: "Read, then test yourself", text: "You get the explanation, the key points, and a couple of follow-up questions. Try answering those from memory before you move on." },
    ],
    boards: "Set your board once and the wording changes. CBSE answers come back as numbered scoring points in NCERT terminology, with numericals laid out Given, To find, Formula, Solution, Answer with units. GCSE (AQA, Edexcel, OCR) answers obey the command word: State gives one fact, Explain gives a linked cause-and-effect chain. AP answers are labelled (a), (b), (c) and tie reasoning to a named course concept. Cambridge IGCSE and International A-Level answers use the exact mark-scheme vocabulary and keep each scoring point separable, with significant figures and units on calculations. WAEC and WASSCE answers are numbered points, each stated then explained in a sentence. If you have not set a board, you get the general method plus a note where boards differ.",
    example: { title: "Explaining a photo of an electrolysis question", body: "You photograph a page on electrolysis of molten lead bromide and type: explain this, I do not get why bromine forms at the anode. Set to Cambridge IGCSE and Long, the answer comes back as: lead bromide must be molten so the ions are free to move; Pb2+ ions move to the cathode and gain 2 electrons; Br- ions move to the anode and lose electrons, so 2Br- becomes Br2 plus 2 electrons. Key points list the half equations. The follow-ups ask you to predict the products for molten zinc chloride and to say why solid lead bromide does not conduct. Answer those two yourself before checking anything, because those are the versions that turn up in the paper." },
    tips: [
      "Photograph one page at a time in good light with the page flat, because a blurry or angled shot is the single most common reason the AI misreads a question.",
      "Type the actual sticking point, such as I do not get why the sign flips at step 3, instead of just explain this, or a vague upload gets a vague explanation.",
      "Set your country, year and board before you start, or the answer will be written in general international terms rather than your board's wording.",
      "Use Short when you are checking one fact mid-revision and Long when you are meeting a topic for the first time.",
      "Close the tab and rewrite the explanation from memory in your own notebook, because reading it back feels like learning but does not stick.",
    ],
    faqs: [
      { q: "Is it really free?", a: "Yes. There is no paid tier, no trial, no card, and no ads. You can use it without an account, although setting your country, year group and exam board makes the explanations much more accurate. There is a daily cap on how many explanations you can run, purely so the running costs stay manageable and the site stays up for everyone." },
      { q: "Can it read a photo of my textbook?", a: "Yes, photos and PDFs both work. Photos are resized automatically so a normal phone picture is fine; PDFs need to be under 3 MB, so upload just the page you need rather than the whole book. It reads printed text well and handwriting reasonably, as long as the shot is sharp and evenly lit. Dark, blurry or steeply angled photos are the usual cause of a wrong reading." },
      { q: "Will it do my homework for me?", a: "It will explain the question, and yes, that often includes working through one. That is not the same as handing in an AI answer, which most schools treat as cheating and which teaches you nothing before the exam, where you are alone with a pen. Use it to understand the method, then close the page and redo the question yourself. If you cannot redo it, you have not learned it yet." },
      { q: "Is it ever wrong?", a: "Yes, sometimes. It can misread a badly lit photo, drop a minus sign, or state something confidently that your syllabus words differently. Treat it like a clever friend explaining at break, not like the mark scheme. Check anything that matters against your textbook or your teacher, and be extra careful with definitions, dates and anything your board words in a fixed way." },
      { q: "What subjects does it cover?", a: "Anything on a school syllabus: maths, the three sciences, English, history, geography, economics, computer science, and languages. It handles equations and chemical formulae properly rather than printing them as broken symbols, and it will draw a small diagram when a process or hierarchy is easier to see than to read. Very niche coursework topics and anything needing your specific school's notes are where it is weakest." },
      { q: "Can I make it explain things more simply?", a: "Yes. There is a tone setting that ranges from kid-friendly to formal exam-prep voice, and a format setting for bullets, paragraphs or step-by-step. You can also pick an interest, such as sport, cooking or gaming, and the examples get pulled from that world instead of generic ones. If an explanation still lands badly, run it again and say which sentence lost you." },
    ],
  },
  "math-solver": {
    slug: "math-solver",
    intro: "Paste a maths problem from your homework or snap a photo of it, and this free step by step math solver writes out every line of working, names the method it used, and flags the mistakes students usually make on that question type. No sign-up, no ads. It shows the working so you can follow it, not copy it.",
    howItWorks: [
      { step: "Give it the problem", text: "Type or paste the question, or upload a photo or PDF of it. Photos need to be in focus and well lit, because a dark or blurry shot gets misread." },
      { step: "Check the restatement line", text: "The solver repeats your problem back in one line before it solves anything. If that line does not match your question, the reading was wrong, so correct it and run it again." },
      { step: "Read the working", text: "You get the named method first, then one short step per operation, then the final answer with its units. Nothing is skipped for being obvious." },
      { step: "Use the pitfalls and checks", text: "Every solution ends with the common mistakes for that question type and a way to verify the answer yourself, usually by substituting it back in." },
    ],
    boards: "Set your board in your profile and the working is laid out the way that board's mark scheme wants it. CBSE numericals come out in the Given, To find, Formula, Solution, Answer with unit layout, with each scoring point kept separate because a 3-mark question wants three of them. GCSE calculations (AQA, Edexcel, OCR) show every line, then the unit and a sensible number of significant figures. AP work is labelled (a), (b), (c) with the setup written out, not just the result. Cambridge IGCSE and International A-Level show-that questions are taken all the way to the given result. WAEC working is numbered and uses syllabus wording. With no board set it teaches the general method rather than guessing conventions.",
    example: { title: "A quadratic that does not look factorisable", body: "Photograph this off a worksheet: solve 2x^2 - 3x - 5 = 0. The solver names the method first, the quadratic formula, then works down one line at a time. Step 1: a = 2, b = -3, c = -5. Step 2: b^2 - 4ac = 9 + 40 = 49. Step 3: x = (3 + sqrt(49)) / 4 or x = (3 - sqrt(49)) / 4. Step 4: x = 5/2 or x = -1. The pitfall it flags: b is -3, so -b is +3, and dropping that sign is where most of the marks go missing on this question type. The check it gives: substitute x = -1, which gives 2 + 3 - 5 = 0, so it holds. It also points out that this one did factorise, as (2x - 5)(x + 1), which would have been faster." },
    tips: [
      "Try the question yourself first and only then compare working, because marks come from producing the steps under exam conditions, not from having read them once.",
      "Read the one-line restatement before you trust anything below it, since a misread photo makes every step after it wrong.",
      "Photograph one question at a time, straight on and in good light, instead of a whole page at an angle.",
      "If a question has parts (a), (b) and (c), paste all of them together, because part (b) usually depends on the answer to part (a).",
      "Cover the screen, write the solution out by hand, then redo the same question a day later to find out whether it actually stuck.",
    ],
    faqs: [
      { q: "Is this step by step math solver really free?", a: "Yes. Every tool on helpinstudy.com is free, with no ads, no paid tier, and nothing held back behind a sign-up. There is a daily cap on how many problems one person can send, because the AI behind it costs money to run, not because there is an upgrade waiting at the end of it. The cap resets the next day." },
      { q: "Can it read a photo of my handwriting?", a: "Usually, if the writing is clear and the photo is sharp and well lit. Fractions, indices, roots and integrals normally read fine. Rushed handwriting, faint pencil, shadows across the page and photos taken at an angle all cause misreads. That is why the solver restates the problem in one line first, so you can catch a bad reading before you follow working for a question you never asked." },
      { q: "Does it ever get the answer wrong?", a: "Yes, it does. It is an AI model, and it slips most often on long multi-part questions, unusual notation, and anything that depends on a diagram it cannot see clearly. Treat the working as a worked example to check yourself against, not as a mark scheme. Every solution ends with a way to verify the answer, and if that check fails, the answer is wrong. Do not hand it in unchecked." },
      { q: "Is using a math solver cheating?", a: "Copying the working into homework you were set to do yourself is cheating, and teachers notice, because the working will not read like yours. Using it to find the exact line where you got lost, then closing the tab and redoing the question from scratch, is just tutoring. What matters is being able to produce those steps in an exam hall, where there is no solver." },
      { q: "What kinds of maths does it handle?", a: "School-level maths up to A-Level and AP: algebra, quadratics, simultaneous equations, indices and surds, trigonometry, coordinate geometry, sequences, vectors, matrices, differentiation and integration, probability and statistics. It also copes with calculation questions from physics and chemistry, such as moles, rates and circuits. Proof-heavy university work and long open-ended modelling questions are outside what it does reliably, so do not lean on it there." },
      { q: "Will the working match what my exam board wants?", a: "If you set your board, largely yes. It follows the layout and command-word habits of CBSE, GCSE (AQA, Edexcel, OCR), AP, Cambridge IGCSE and International A-Level, and WAEC. With no board set it teaches the general method and shows full working, which earns marks on any of them. It cannot know your school's house style or your teacher's preferred notation, so adjust those yourself before you write up." },
    ],
  },
  "quiz": {
    slug: "quiz",
    intro: "Paste a page of notes, or upload a photo or PDF of a textbook page, and this free AI quiz generator from notes writes 4 to 20 practice questions on it: multiple choice, short answer, true or false, and fill in the blank. Answers stay hidden until you ask for them, and every one comes with a why.",
    howItWorks: [
      { step: "Paste or upload notes", text: "Paste 300 to 800 words of your own notes, or upload a sharp photo or PDF of one textbook page. One section produces far better questions than a whole chapter." },
      { step: "Choose how many questions", text: "The slider runs from 4 to 20. Ten is about right for a single revision sitting, and small enough that you will actually finish it." },
      { step: "Answer the whole set", text: "Work through every question before you check anything. Nothing is revealed until you press Show answers, which is the point." },
      { step: "Reveal answers and reasons", text: "Multiple choice and true or false show the correct option with a one-line why. Short answer and fill in the blank show the model answer and a marking rubric so you can mark yourself." },
    ],
    boards: "Set your board on the profile screen and the phrasing changes. Cambridge IGCSE and International A-Level questions use the real command words (State, Describe, Explain, Suggest, Show that) and expect the exact syllabus term rather than a paraphrase. GCSE questions for AQA, Edexcel and OCR are point-marked, so an Explain item wants a linked cause-and-effect chain and a Calculate item wants units and sensible significant figures. CBSE leans on NCERT wording, a three-mark question expects three separate points, and numericals are set out as Given, To find, Formula, Solution. AP uses task verbs with parts labelled (a), (b), (c) and reasoning tied to a course concept. WAEC expects numbered points, each explained in one sentence.",
    example: { title: "Eight questions from one page of moles notes", body: "I pasted about 400 words of my Chemistry notes on moles and gas volume and asked for eight questions. The multiple choice one wanted the volume of 0.25 mol of carbon dioxide at room temperature. The answer was 6 dm3, with 0.25 x 24 shown in the why line, and the tempting wrong option was 96 dm3, which is what you get if you divide instead of multiply. The fill in the blank was 'One mole of any gas occupies ___ dm3 at room temperature and pressure.' The short answer asked why the same mass of oxygen and hydrogen do not occupy the same volume, and the rubric wanted the words relative molecular mass. I got the first two right in under a minute and lost the short answer, because I never wrote that phrase. It is the phrase the mark scheme wants." },
    tips: [
      "Paste one section of 300 to 800 words rather than a whole chapter, because ten questions spread over forty pages will only ever test the easiest surface facts.",
      "Answer every question before you press Show answers, since recognising a right answer feels like knowing it and is not the same thing.",
      "Write short answers out in full on paper first, then compare them to the rubric line by line and count how many separate scoring points you actually made.",
      "Check anything that surprises you against your own textbook, and if a correct answer contains a detail you never wrote down, that question came from the model rather than your material.",
      "Two days later, paste only the parts of your notes covering the questions you got wrong and generate a fresh set from those.",
    ],
    faqs: [
      { q: "Is the quiz generator free?", a: "Yes, completely. There is no paid tier, no trial and no ads, and you do not need an account to make a quiz. There is a daily limit on how many quizzes one visitor can generate so the site stays up, and it resets each day. Signing in is optional and mainly exists so your board and grade stick between visits." },
      { q: "Does it mark my answers automatically?", a: "Multiple choice and true or false are marked for you: the correct option is highlighted and a one-line why explains it, including why the tempting wrong option was tempting. Short answer and fill in the blank show the model answer plus a marking rubric, and you mark yourself against that rubric. There is no score out of ten and no running record of past quizzes." },
      { q: "Can I upload a photo of my textbook or a PDF?", a: "Yes. A photo or a PDF page works as well as pasted text, as long as it is sharp and evenly lit. Dark, blurry or angled photos get misread, and a misread line becomes a wrong question. If handwriting is small or faint, typing the notes out is quicker than fixing the quiz afterwards. Diagrams are read as pictures, so label-heavy pages produce weaker questions than prose." },
      { q: "How accurate are the questions and explanations?", a: "Good, but not perfect. Most questions come straight from what you pasted, but the model sometimes pulls in a fact from its own knowledge, or writes an answer that is technically right and worded in a way your examiner would not credit. Treat every explanation as a draft to check against your textbook. If an answer contains a detail that is not in your notes, drop that question rather than learning it." },
      { q: "Is using an AI quiz generator cheating?", a: "Making practice questions from your own notes and answering them yourself is revision, not cheating. Handing the tool your homework so it writes the answers for you is a different thing, and it will show up in your next test. The point of a quiz is to find out what you cannot yet do while there is still time to fix it, which only works if you answer honestly." },
      { q: "Does it build a study plan or track my progress?", a: "No. This page does one job: it turns material you give it into practice questions with explanations. It does not build a timetable, read your syllabus, predict a paper, or keep a record of your scores over time. If you want spaced repetition, make flashcards from the questions you got wrong, and if you want a timed full paper, use the mock exam tool instead." },
    ],
  },
  "grade": {
    slug: "grade",
    intro: "Paste an exam-style question and the answer you wrote, and this free tool marks it the way an examiner would: a score out of the marks available, the marking points you hit, and the ones you missed. AI exam answer marking for CBSE, GCSE, AP, Cambridge and WAEC. It is practice feedback, not an official grade.",
    howItWorks: [
      { step: "Paste the question", text: "Copy it exactly as the paper prints it, command word and marks included. The mark total tells the marker how many separate scoring points to look for." },
      { step: "Add your own answer", text: "Type or dictate what you actually wrote, half-sentences and missing units included. Tidying it up first hides the marks you are really losing." },
      { step: "Add the mark scheme", text: "Optional, but if you have the official scheme from a past paper, paste it and your answer is checked against those exact criteria instead of general ones." },
      { step: "Read what you missed", text: "You get a score out of the marks, a band, the points that earned credit, the points that did not, and a model answer to compare against line by line." },
    ],
    boards: "CBSE answers are point-marked, so a 3-mark question is checked for three separate scoring points, and numericals are checked for the Given, To find, Formula, Solution, Answer layout. GCSE marking (AQA, Edexcel, OCR) turns on the command word: Describe earns credit for what happens, Explain only for a linked cause-and-effect chain. AP free response is scored against rubric points, so labelling parts (a), (b) and (c) and tying reasoning to a named course concept both matter. Cambridge IGCSE and International A-Level schemes reward exact terminology, so an everyday paraphrase that means the same thing still loses the point. WAEC and WASSCE theory answers are checked as numbered points, each one stated and then explained in a sentence.",
    example: { title: "A 6-mark Explain question, marked", body: "Question pasted in: Explain why the rate of a reaction increases when the temperature rises (6 marks). Answer pasted in: Particles move faster when it is hotter, so they collide more often and the reaction speeds up. It comes back at 2 out of 6. Marking points hit: particles gain kinetic energy; collision frequency increases. Marking points missed: more particles have energy above the activation energy; a greater proportion of collisions are therefore successful; no mention of successful collisions at all. The feedback names the real problem, which is that the answer describes rather than explains, and Explain wants a linked chain. The same student rewriting it with activation energy in the chain reaches 5. The gap was exam technique, not chemistry." },
    tips: [
      "Always include the marks in the question, because a marker looking for six scoring points reads your answer very differently from one looking for two.",
      "Mark the answer yourself first, then run it here, and treat any gap between your score and the tool's as the thing worth studying.",
      "Do not clean up your answer before pasting it, since the missing units and vague verbs are exactly where the marks went.",
      "When the same command word keeps costing you marks, break the model answer apart and count how many separate scoring ideas are actually in it.",
      "Use it on answers you wrote under timed conditions rather than on questions you have not properly attempted yet.",
    ],
    faqs: [
      { q: "How accurate is AI exam answer marking?", a: "It is reasonably close on point-marked factual questions where the scoring points are objective, and much shakier on long essays, where two real examiners would disagree with each other anyway. The score is a rough signal; the list of missed marking points is the genuinely useful part. Pasting the official mark scheme from a past paper improves accuracy a lot, because it then checks against real criteria." },
      { q: "Is the score the same as my real grade?", a: "No. A real grade depends on grade boundaries that shift every session, on the whole paper rather than one answer, and on an examiner's judgement about borderline points. The band shown here is an estimate for a single answer in isolation. Use it to find the technique you are missing, not to predict a result. Your teacher's marking on your own board's paper is still the more reliable number." },
      { q: "Do I need the official mark scheme?", a: "No, it works without one and applies typical criteria for your board. But pasting the mark scheme from a past paper makes the marking noticeably fairer, especially in the sciences, where the scheme accepts one specific term and rejects a close synonym that means much the same thing. If you already have the paper open, paste it in." },
      { q: "Which exam boards does it work with?", a: "CBSE, GCSE (AQA, Edexcel and OCR), AP, Cambridge IGCSE and International A-Level, and WAEC or WASSCE. Set your board once and the marking follows that board's conventions: point-marked short answers for CBSE and WAEC, command-word logic for GCSE and Cambridge, rubric points for AP. With no board set it marks to general criteria, which still checks your method but is weaker on wording." },
      { q: "Can it just write the answer for me?", a: "It shows a model answer so you can compare structure, but the tool exists to mark what you wrote, not to hand you something to copy. Submitting AI-written work as coursework counts as malpractice on every board listed here, and it skips the only step that actually raises your marks, which is seeing what your own answer left out. Write first, then mark." },
      { q: "Is it free, and is there a limit?", a: "It is free, with no paid tier and nothing locked behind an account. There is a daily cap on marking runs so the site stays affordable to run, which is enough for a normal revision session rather than an entire past paper in one sitting. Setting your board and year takes a few seconds and makes the marking match your actual paper more closely." },
    ],
  },
  "mock-exam": {
    slug: "mock-exam",
    intro: "A free mock exam generator that writes a fresh practice paper on any topic you name, in the style of your board, then times you while you sit it. Choose how many questions and how long you get, submit, and every question comes back marked with the correct answer and the reason behind it.",
    howItWorks: [
      { step: "Set your exam board", text: "Onboarding takes about 30 seconds and stores your country, board and year, and the paper is written to that. Skip it and you still get a paper, just written in general terms instead of guessing between CBSE and AQA conventions." },
      { step: "Pick topic and timing", text: "Type a topic such as trigonometric identities, electrolysis or the cold war, then set between 5 and 30 questions and anywhere from 5 to 180 minutes. Copy the ratio of your real paper rather than the time you feel like giving it." },
      { step: "Sit it under the clock", text: "The countdown sits at the top of the screen and submits the paper for you when it hits zero. No pausing, no notes open in another tab, because the whole point is finding out what you can do without them." },
      { step: "Read the marking, not the score", text: "Every question opens up to show your answer, the correct answer and why it is correct. The useful part is the pattern across the ones you lost, not the number at the top." },
    ],
    boards: "Your board changes the questions, not just the topic list. CBSE papers are point-marked, so short answers expect roughly one scoring point per mark, and numericals follow the Given, To find, Formula, Solution, Answer with units layout. GCSE questions from AQA, Edexcel and OCR turn on command words: state wants one fact, explain wants a linked cause and effect chain. AP items use College Board task verbs and course terminology, labelled by part. Cambridge IGCSE and International A-Level mark schemes reward exact key terms, so a describe question will not accept an everyday paraphrase. WAEC theory questions expect numbered points, each stated and then explained in a sentence.",
    example: { title: "A 30-minute trigonometry mock, and what it actually caught", body: "I set the topic to trigonometric identities, 12 questions, 30 minutes, which is close to the marks-per-minute of my real paper. One question asked me to show that (1 - cos^2 x) / sin x simplifies to sin x. I wrote sin x and moved on. The review screen counted it correct, but the reason line said the marks come from stating sin^2 x + cos^2 x = 1 first, then cancelling. That is exactly the mark I would drop in June. Two more questions went the same way: right answer, missing line of working. So the score, 10 out of 12, was the least useful thing on the page. The pattern was that I skip the identity I am quoting. That went in my error log; the score did not." },
    tips: [
      "Set the clock to your real paper's ratio, roughly a minute and a half per mark on most written papers, instead of whatever feels comfortable.",
      "Sit the whole thing in one go with your phone in another room, because a mock you pause is just a worksheet.",
      "Write short answers in full exam wording even when a couple of words would pass the marker, since the wording is what gets marked in the real paper.",
      "After marking, write down the reason you lost each mark rather than the total, then generate a second paper on only those topics.",
      "Reach for this when you have worked through the past papers your board has released, not instead of them.",
    ],
    faqs: [
      { q: "Is the mock exam generator actually free?", a: "Yes. Every tool on the site is free, there is no paid tier, no trial and no ads. You do not need an account to generate a paper or to sit it. There is a daily limit on how many papers you can generate, which exists to keep the running costs manageable rather than to push you towards paying, and it resets the next day." },
      { q: "Are these real past papers from my board?", a: "No, and that difference matters. Questions are written fresh in your board's style and at exam difficulty, but they are not published by CBSE, AQA, Edexcel, OCR, Cambridge, the College Board or WAEC, and no leaked paper is involved. Official past papers are still better practice because their mark schemes are real. It also cannot predict what will come up this session." },
      { q: "How long should I set the timer for?", a: "Match your real paper's ratio rather than your patience. Most written papers run near a minute and a half per mark, so a 12-question set of short items sits around 20 to 30 minutes. If you are building stamina for a two-hour paper, set 30 questions and the full two hours once a fortnight instead of doing short sets every day." },
      { q: "My short answer was right but it was marked wrong. Why?", a: "That happens. Short answer and fill-in-the-blank responses are checked against the expected wording, so a correct answer phrased differently can come back with a cross. Open the question, compare your line with the answer and the reason given, and count it yourself. Worth noticing anyway: most mark schemes reward specific terms, so a paraphrase that fails here often loses marks in the real paper too." },
      { q: "Can it mark essays or long written answers?", a: "Not here. This tool builds multiple choice, true or false, short answer and fill-in-the-blank questions, which auto-mark cleanly. For a six-mark explanation, a source question or a full essay, write it out and put it through the grading tool instead, which marks in your board's mark-scheme style and tells you which point was missing. Different jobs, and both are free." },
      { q: "Is using an AI mock exam cheating?", a: "Sitting a practice paper under a clock and marking yourself honestly is the opposite of cheating, it is just revision. What would be cheating is generating questions to dodge the ones your teacher set, or copying answers out of the review screen into homework. This exists to show you where your marks leak before the real paper does, not to produce work with your name on it." },
    ],
  },
  "flashcards": {
    slug: "flashcards",
    intro: "This is a free AI flashcard generator with spaced repetition built in. Paste a topic, a chunk of your notes, or a photo of a textbook page, and it writes question-and-answer cards for you. Every card you review is then scheduled by the SM-2 algorithm, so it returns just before you would forget it.",
    howItWorks: [
      { step: "Give it your material", text: "Type a topic like electrolysis, paste a lesson, or upload a clear photo or PDF of your notes. Choose how many cards you want, from 5 up to 20." },
      { step: "It writes the cards", text: "The AI turns that material into short question-and-answer pairs. It uses the terminology of the exam board set in your profile, so the wording matches what your paper expects." },
      { step: "Flip and grade yourself", text: "Tap the card to see the answer, then press Again, Hard, Good or Easy. The whole schedule runs off that button, so grade what actually happened in your head, not what you wish had happened." },
      { step: "SM-2 picks the next date", text: "A card you get right comes back in 1 day, then 6 days, then in gaps that keep stretching. Press Again and it drops straight back to tomorrow's pile." },
    ],
    boards: "Set your board in your profile and the cards follow its wording. CBSE cards drill NCERT definitions and one-mark answers, with SI units on every numerical. GCSE cards for AQA, Edexcel and OCR separate recall you must memorise from equations printed on the physics sheet, and they respect command words: state, describe, explain. AP cards lean on unit vocabulary and the reasoning stems free response questions ask for, since your formula sheet is supplied anyway. Cambridge IGCSE and International A-Level cards track syllabus definition wording closely, because that is where the one and two mark definitions live. WAEC cards front-load Paper 1 objectives: definitions, formulae and labelled diagram parts.",
    example: { title: "One chemistry page turned into a fortnight of review", body: "You photograph the electrolysis page in your notes and ask for 12 cards. Back come pairs like: front, what is discharged at the cathode in molten lead bromide? Back, lead, because cations are reduced there. You flip the first card, get it wrong and tap Again, so it returns tomorrow. Next day you get it right, and SM-2 gives it 1 day. Right again and the gap jumps to 6 days. After that each interval is multiplied by an ease factor starting at 2.5, so a card you keep getting right runs 1, 6, 15, then 38 days. Ten minutes of work on Monday becomes a two-minute top-up the following week, while the cards you keep failing stay on tomorrow's pile, which is where your revision time should be going." },
    tips: [
      "Generate cards right after a lesson while the material is fresh, then do the first review the next day rather than the same evening.",
      "Keep one fact per card. If the answer runs to three lines, split it into three cards, because a card you can only half-recall gets graded dishonestly.",
      "Do the due pile every day even when it is only six cards, since skipping a week makes everything fall due at once.",
      "Use flashcards for recall only: definitions, formulae, units, dates, diagram labels. Full exam questions still have to be written out on paper with working shown.",
      "Read the first few generated cards against your own notes before you trust the deck, because a misread photo produces confident wrong answers.",
    ],
    faqs: [
      { q: "Is this AI flashcard generator really free?", a: "Yes. Every tool on helpinstudy.com is free, there are no ads, and there is no paid tier sitting behind it. Card generation is rate limited to a sensible number of runs per day so that one person cannot drain the AI quota for everyone else, but nothing is locked behind payment. You do not need an account to generate cards or to review them." },
      { q: "What is SM-2 and why do the gaps keep growing?", a: "SM-2 is the spacing algorithm behind most serious flashcard apps. Each card carries an ease factor that starts at 2.5. Get a card right and the wait runs 1 day, then 6 days, then the previous interval multiplied by that ease. Get it wrong and the card resets to tomorrow. The idea is to meet a card just as it fades, since recall that takes effort is what actually sticks." },
      { q: "Where are my cards stored, and can I lose them?", a: "Cards are saved in your browser's storage on the device you made them on, which is why no sign-in is required. It also means clearing your browser data, or switching from laptop to phone, leaves them behind. If you do sign in, newly generated cards are saved to your account as well so they follow you across devices. There is no export file yet, so treat a big deck as device-specific." },
      { q: "Can it make cards from a photo of my notes?", a: "It reads clear photos and PDFs, and tidy handwriting in even light usually works. Blurry, dark or steeply angled shots produce nonsense cards, and the AI will not warn you that it misread something, it will simply write a confident wrong answer. Check the first few cards against the original page before you start drilling, and rephotograph anything that came out garbled." },
      { q: "Is using an AI flashcard generator cheating?", a: "Making cards from your own material and then testing yourself is revision, not cheating. The line sits at who does the thinking. If you never read the source and only flip cards, you end up memorising sentences you do not understand, which collapses the moment an exam asks you to apply the idea. Generate from a lesson you have already sat through at least once." },
      { q: "How many cards should I make in one go?", a: "The slider runs from 5 to 20 per generation, and 10 to 15 from a single lesson is usually about right. Big decks feel productive on the day you build them and punishing a week later when 60 cards come due together. Build small topic decks across several days instead, so the reviews spread out rather than stacking into one miserable session." },
    ],
  },
  "chat": {
    slug: "chat",
    intro: "HelpInStudy's free AI tutor chat answers any study question, then lets you keep asking follow-ups until the topic actually clicks. Set your exam board once and every reply comes back in CBSE, GCSE, AP, Cambridge or WAEC style, matching the command words and working your marker wants. No sign-up, no payment.",
    howItWorks: [
      { step: "Set your exam board", text: "Onboarding asks for your country, year group and board, and takes about thirty seconds. Skip it if you like; the chat still works, it just answers in a board-neutral way." },
      { step: "Ask your question", text: "Type it or use the mic, in whatever words you would use out loud. Include the mark allocation if the question has one, because a 2-mark answer and a 6-mark answer look nothing alike." },
      { step: "Keep asking follow-ups", text: "This is the part that matters. Ask why a step happened, ask for a smaller example, ask for it in your board's wording, and keep going until it genuinely clicks." },
      { step: "Check it without the chat", text: "Close the tab and redo the question from a blank page. That is the only proof the explanation landed, and it is also the line between using a tutor and cheating." },
    ],
    boards: "CBSE replies are point-marked, so a 3-mark question comes back as three numbered points in NCERT wording, and numericals follow Given, To find, Formula, Solution, Answer with units. GCSE answers for AQA, Edexcel and OCR obey the command word: Explain returns a linked cause-and-effect chain, Describe does not. AP replies label parts (a), (b), (c) and tie every justification to a named course concept, with no warm-up sentence. Cambridge IGCSE and International A-Level answers use the exact syllabus term rather than a paraphrase, because the mark scheme rewards the word. WAEC theory answers are numbered, each point stated then explained in one sentence. With no board set, it teaches the general method and flags where boards differ.",
    example: { title: "One question, four follow-ups", body: "Start with the question you actually have, not a tidy version of it. Ask: explain why the rate of a reaction slows down as it goes on. The first reply gives the collision-theory chain. Then keep going. Why does the concentration drop if nothing is removed? Is it the same reason when the reactant is a solid? Write that the way a 4-mark Explain question wants it. Now give me one and mark my answer. Each follow-up is one step narrower than the last, which is what makes it stick. The same loop works on a calculation: ask for the method on 2x^2 - 3x - 5 = 0, then ask why the discriminant predicted two roots, then do the next question with the chat closed." },
    tips: [
      "Paste the whole question including the marks, because the same topic asked for 2 marks and for 6 marks needs completely different answers.",
      "Say exactly which bit lost you, so ask why the 2 disappeared in line three rather than saying you do not understand.",
      "When a reply makes sense but you could not have written it yourself, ask it to set you a similar question and mark your attempt instead of moving on.",
      "Use the Short setting for quick checks mid-revision and Long when you are meeting a topic for the first time.",
      "Ask it to show every step and state the units, then compare that working against your own so you can see where yours diverges.",
    ],
    faqs: [
      { q: "Is the AI tutor chat really free?", a: "Yes. There is no paid tier, no trial, no card and no ads. You can use it without an account. Signing in only adds saving your conversations to your account, so you can pick a topic up on another device. The guest version keeps your conversation in your own browser and forgets it when you press Clear history. There is a daily message limit to stop bots draining it, which ordinary revision does not reach." },
      { q: "Will it just do my homework for me?", a: "It will answer the question, and if you copy that answer into your book you have learned nothing and your teacher will usually know. The chat is built to show the method, and when you look stuck it asks a guiding question before handing over the full answer. The honest test: close the tab and reproduce your answer from a blank page in twenty minutes. If you cannot, you have not learned it and should not submit it." },
      { q: "How does it know which exam board I sit?", a: "You tell it once. Onboarding asks for your country, year group and board, and takes about thirty seconds. That choice is stored on your device and applied to every reply afterwards. Without it the chat stays deliberately board-neutral: it teaches the correct general method and says where boards differ rather than guessing, because assuming GCSE conventions would mislead a CBSE or WAEC student. You can change the board any time in settings." },
      { q: "Can the answers be wrong?", a: "Yes, and you should plan for it. It can state a confident wrong number, misremember a syllabus detail, or give a definition your board words differently. Check anything you will be marked on against your textbook, your specification or your teacher. Use it for method and understanding first, and treat any fact you cannot verify as a lead to check, not a finished answer. Asking it to show its working also makes a wrong step much easier to spot." },
      { q: "Does it remember what we talked about?", a: "Within a conversation, yes. It keeps the recent turns in full plus a short summary of older ones, so you can say go back to the second step without repeating yourself. Guest conversations live in your own browser on that one device and disappear when you press Clear history or clear site data. Signed-in conversations are saved to your account, so you can return to a topic days later." },
      { q: "What can it not do?", a: "It has no file or photo upload, so screenshots and PDFs belong in the Explain or Math solver tools instead. It will not build you a revision timetable, produce a study plan, read your school's own scheme of work, or predict what is on this year's paper. It also has no view of your marks. It is one thing: questions, answers, and as many follow-ups as you need." },
    ],
  },
  "essay-coach": {
    slug: "essay-coach",
    intro: "Essay coach is free AI essay feedback for students who want to understand why an essay scores, not have one written for them. Plan a structure, write it paragraph by paragraph, and paste each part back for feedback pointed at what your examiner's mark scheme actually rewards: judgement, linked reasoning, evidence.",
    howItWorks: [
      { step: "Plan the structure", text: "Paste the exact question or title and ask for an outline. You get an introduction, three body paragraphs with topic sentences and a conclusion, which you then argue with rather than accept." },
      { step: "Choose a thesis", text: "Ask for thesis options and you get three, ranked from safe to bold, each with a line on why it works. Opening hooks work the same way if your introduction will not start." },
      { step: "Draft one paragraph at a time", text: "Write a paragraph yourself, paste it back, and ask what is weak. Feeding an essay through in pieces gets far more specific feedback than pasting nine hundred words in at once." },
      { step: "Get examiner-style feedback", text: "On a full draft you get what works, where the argument goes soft, three line edits and a stronger thesis to try. Nothing gets rewritten for you, so the editing is still your work." },
    ],
    boards: "Set your board in the profile and the feedback changes with it. GCSE and A-Level (AQA, Edexcel, OCR) feedback chases the command word and linked reasoning, so an Explain paragraph gets checked on whether the chain actually runs cause to effect. Cambridge IGCSE and International A-Level feedback tests whether you answered the exact command word and kept each scoring point separable. AP feedback looks for a defensible thesis plus evidence and reasoning tied to course concepts, with parts labelled a, b, c. CBSE feedback pushes numbered points matched to the mark allocation and NCERT terminology. WAEC feedback wants each point stated and then explained, numbered, in the direct marking-scheme style.",
    example: { title: "A Macbeth paragraph, before and after", body: "You are writing on how Shakespeare presents ambition in Macbeth. You draft one paragraph, paste it in, and ask where the argument is weak.\n\nBefore: Macbeth says he has vaulting ambition. This shows he is ambitious and that his ambition is very strong, which leads him to kill Duncan.\n\nThe feedback names the problem: the quotation is repeated, not analysed, and the paragraph never says what the writer is doing. It suggests you take one word and tie it to the play's argument.\n\nYou rewrite it yourself.\n\nAfter: The metaphor of vaulting turns ambition into a physical leap, and Macbeth's own image admits it overleaps and falls. Shakespeare lets him diagnose his ruin before he acts, so the murder reads as chosen, not fated.\n\nSame quotation, same length. The difference is that the second version has an idea in it." },
    tips: [
      "Paste the exact question wording rather than your summary of it, because the feedback can only check whether you answered the question it can see.",
      "Ask for feedback one paragraph at a time; a whole essay pasted in one block gets general comments, while a single paragraph gets specific ones.",
      "Say your board and the mark allocation, since a 6-mark GCSE answer and a 25-mark A Level essay want completely different shapes.",
      "Ask the awkward question directly: does this paragraph state a criterion for why one factor outweighs another, or does it only describe?",
      "Retype the improved sentences in your own words instead of copying anything back, because you will sit the real paper without the coach.",
    ],
    faqs: [
      { q: "Will it write my essay for me?", a: "No, and that is deliberate. It plans structures, offers thesis options, suggests openings and tells you where a paragraph goes weak, but the sentences that end up in your essay have to be yours. Handing in AI-written work counts as malpractice on every board here, and more practically, you will sit the real paper without it. Use it to see the gap, then close the gap yourself." },
      { q: "Is the AI essay feedback free?", a: "Yes. There is no paid tier, no trial and no card. You do not need an account either, though setting a profile with your board and year makes the feedback match your mark scheme instead of a generic one. There is a daily cap on AI requests so the running costs stay manageable, and it resets the next day." },
      { q: "Can it give my essay a grade?", a: "Not on this page, and any number it gave you would be a guess anyway. Real marking depends on the specific paper, the mark scheme and a moderated examiner. What the coach does is tell you which paragraph is doing the least work, which is usually more useful. If you want a rough band with reasoning, mark my answer at /grade is a separate tool." },
      { q: "What does it actually check a paragraph against?", a: "It looks at the things mark schemes credit rather than at style: whether you answered the command word, whether each claim carries specific evidence, whether the reasoning is linked rather than listed, and whether the paragraph gets back to the question. It only knows what you paste, so if you want it judged against a particular criterion, name that criterion in the box and it will answer that instead." },
      { q: "What is it bad at?", a: "Three things worth knowing. It has not seen your teacher's mark scheme, so treat any talk of bands as an opinion. It cannot verify a quotation or a statistic, so check your evidence yourself before you hand anything in. And it is weakest on set texts and case studies covered in class, where your teacher's specific reading matters more than a general one." },
      { q: "Does it help with grammar and referencing too?", a: "Yes, on the same page. The grammar check gives you a corrected version plus a list of what changed and why, so you can see the pattern in your own errors instead of just accepting a fix. The citation tab builds a reference in APA, MLA, Chicago or Harvard from five fields, and it runs as a plain formatter in your browser rather than through the AI." },
    ],
  },
  "lecture-summary": {
    slug: "lecture-summary",
    intro: "Paste a lecture, a transcript or a long set of notes, and this free tool turns it into clean revision notes: key points, the definitions that matter, and what is worth memorising. If you have been looking for a way to summarise lecture notes, AI handles the compression; you still have to do the learning.",
    howItWorks: [
      { step: "Paste the material", text: "Drop in the lecture transcript, your class notes or a long stretch of textbook. You can also upload the slide PDF or a clear photo of a page if that is what you have." },
      { step: "Set your board once", text: "Pick CBSE, GCSE, AP, Cambridge or WAEC and your year. The notes then come back in that board's wording rather than generic textbook English." },
      { step: "Read what comes back", text: "You get the key points, the definitions worth knowing, and a few questions the topic normally gets asked as. It is a page, not an essay." },
      { step: "Turn it into recall", text: "Cover the page the same day and rewrite the key points from memory. Whatever you cannot recall becomes your gap list, and that list is the actual revision." },
    ],
    boards: "Set your board once and the notes come back in that board's language. For CBSE it keeps NCERT chapter wording, because 3 and 5 mark answers are marked on keywords. For GCSE (AQA, Edexcel or OCR) it tags points by command word, so you can see which lines answer describe and which answer explain in a 6 mark levels of response question. For AP it groups points by unit and flags what an FRQ would ask you to justify. For Cambridge IGCSE and International A Level it holds definitions in syllabus wording, since mark schemes there accept very little paraphrase. For WAEC it splits points into short numbered lines, which is how WASSCE theory answers earn marks.",
    example: { title: "What it looked like for one enzymes lecture", body: "I pasted in the transcript of a 40 minute biology lecture on enzymes, about 6,000 words of talking. Back came roughly 400 words: eight key points, six definitions (active site, induced fit, competitive inhibition, non competitive inhibition, Vmax, Km), and three questions the topic normally gets asked as. The useful bit was Km. My own notes had it as how fast the enzyme works, which is wrong, and I would have written that in a test. The summary had it as the substrate concentration at which the rate is half of Vmax, which is the version a mark scheme accepts. Then I covered the page and rewrote the eight points from memory. I got five. The three I missed went into flashcards, and that step, not the summarising, is what made them stick." },
    tips: [
      "Summarise after the lesson, never instead of it, because if the summary is the first time you meet the material you are learning it the slowest possible way.",
      "Type the topic name or the exact syllabus point at the top of what you paste, so the notes come back scoped to what your board examines rather than everything the lecturer happened to mention.",
      "Run one topic at a time; a whole term pasted at once comes back as headings with almost nothing underneath them.",
      "Check every definition and any numbers against your textbook before you memorise them, because a confidently wrong line is worse than a blank.",
      "Within a day, cover the summary and rewrite the key points from memory, then keep only the ones you missed as flashcards.",
    ],
    faqs: [
      { q: "Is it actually worth using AI to summarise lecture notes?", a: "For compressing an hour of talking into a page you can revise from, yes, it saves real time. For learning the material, no, because reading a summary feels like understanding and is not. Use it to get the raw material into a usable shape, then close it and rewrite the key points from memory. The second part is where the marks come from." },
      { q: "Is it free, and do I need an account?", a: "It is free and there is no paid tier waiting behind it. You do not need an account to use it; you set your board and year once so the notes come back in the right style, and that is stored on your device. There is a daily cap on how many runs one device gets, because the AI costs money to run. Signing in raises the cap and syncs your work across devices." },
      { q: "How accurate are the definitions it gives me?", a: "Good enough to revise from, not good enough to trust blind. Two failure modes come up often: it states a definition in general terms when your board wants a specific form of words, and it repeats a mistake that was already in your notes, confidently. Check every definition and every number against your textbook or the syllabus before you commit it to memory." },
      { q: "Can I upload a PDF of the slides or a photo of my notes?", a: "Yes. A PDF has to be under 3 MB, so upload the pages you need rather than the whole deck, and photos need to be sharp and well lit because the AI reads them the same way you would. Handwriting is the weak point: neat notes usually come through, but a rushed page scribbled in the margin often gets misread or skipped entirely." },
      { q: "Is using this cheating?", a: "Summarising a lesson you sat through is revision, the same as borrowing a friend's notes. Pasting the summary into a piece of assessed work and calling it yours is not, and most schools now treat that the same as copying. The line is simple: use it on material you are trying to learn, never on work that is being marked." },
      { q: "How much text should I paste at once?", a: "One topic at a time. A single lecture or one chapter comes back with enough detail to revise from; a whole term pasted in one go comes back as headings with nothing under them, because the model has to cut somewhere. If your transcript covers three topics, run it three times and you will get three usable pages instead of one thin one." },
    ],
  },
  "transform": {
    slug: "transform",
    intro: "If you want to explain a topic using your interests, pick one — cricket, cooking, gaming, football, K-pop — and any topic gets re-explained through that lens. The analogy carries the idea, the exam wording stays intact. It is free, needs no sign-up, and works on typed questions, photos or PDFs.",
    howItWorks: [
      { step: "Pick your interest", text: "Choose from the presets (cricket, cooking, gaming, football, K-pop, Minecraft, anime, cars and more) or type your own, like chess or Formula 1. A specific interest gives sharper examples than a broad one." },
      { step: "Choose theme strength", text: "Four settings: Off, Light touch (one or two themed examples), Heavily themed (most examples from your world), and Full reframe (the whole explanation set inside it, ending with a plain-words line naming the real concept)." },
      { step: "Add the topic", text: "Type the question, paste a paragraph, speak it, or upload a clear photo or PDF of the page. Blurry or dark photos cannot be read, so use good light." },
      { step: "Translate it back", text: "You get the themed explanation plus key points and follow-up questions. Close it and say the same thing in syllabus words before you move on." },
    ],
    boards: "Set your country, board and grade and the themed answer still follows that board's marking habits. CBSE answers arrive as numbered scoring points in NCERT terminology, with numericals in the Given, To find, Formula, Solution, Answer layout. GCSE answers (AQA, Edexcel, OCR) obey the command word, so an Explain becomes a linked cause-and-effect chain. AP answers label parts (a), (b), (c) and tie reasoning to a named course concept. Cambridge IGCSE and International A-Level answers use exact command words and precise syllabus vocabulary, because the mark scheme rewards the term itself. WAEC answers come as numbered points, each stated then explained in a sentence. With no board set, you get the general method and a note where boards differ, rather than invented wording.",
    example: { title: "Electromagnetic waves, explained through cooking", body: "Interest: cooking. Theme strength: heavily themed. Topic: if a radio wave and a microwave are both electromagnetic, why does only one cook food? The answer comes back as a kitchen. The spectrum is a hob dial, wavelength shrinking as you turn from radio to microwave to infrared to visible. Water molecules are the pan: a microwave field near 12 cm flips about 2.5 billion times a second and drags those polar molecules round with it, and that movement is the heat. Radio waves do not grip them. Then the plain-words line names the real concept, absorption. Before you close the tab, write the exam version yourself using c = f x lambda and the word absorption, because that is the sentence the marker reads, not the hob dial." },
    tips: [
      "Start on Light touch for a topic you nearly understand, and save Full reframe for the one that has never made sense.",
      "After reading the themed version, close it and rewrite the explanation in syllabus words; if you cannot, the analogy gave you a story rather than the concept.",
      "Never put the analogy in an exam answer, because markers award the technical term: the water molecules absorb the energy earns the mark, the pan rattles earns nothing.",
      "If the analogy starts feeling forced, that is usually the point where the two things stop matching, so ask a follow-up about where the comparison breaks down.",
      "Pick a narrow interest over a broad one, since a cricket run chase produces better examples than sport.",
    ],
    faqs: [
      { q: "How do I explain a topic using my interests here?", a: "Pick an interest from the presets or type your own, choose how strong the theme should be, then add your topic as text, voice, a photo or a PDF. The tool rewrites the explanation through that lens and gives you key points and follow-up questions. Cricket, cooking, gaming, football and K-pop are on the list, and a custom interest like chess or Formula 1 works just as well." },
      { q: "Does the analogy replace the real explanation?", a: "No. Light touch keeps a neutral explanation and adds one or two themed examples. Heavily themed pulls most examples from your world. Full reframe sets the whole thing inside it and then finishes with a plain-words sentence stating the academic concept, so you are never left holding only a story. Whichever level you choose, the proper concept is named somewhere in the answer." },
      { q: "Can I write the analogy in my exam answer?", a: "No, and it would cost you marks. Mark schemes across CBSE, GCSE, AP, Cambridge and WAEC reward precise terminology, so you write absorbs infrared radiation, not like a pan on the hob. The themed version is for getting the idea into your head. Turning it into the exam sentence is a separate job, and doing that translation yourself is most of the actual learning." },
      { q: "What does this tool not do?", a: "It only re-explains a topic through an interest. This page does not build a study plan or a timetable, does not take a syllabus upload, and does not track your revision. Some material also resists a good analogy: abstract proofs, formal definitions and vocabulary lists often come out worse themed than plain. When that happens, set the theme to Off and read it straight." },
      { q: "Is it free, and do I need an account?", a: "It is free, with no account required, no card and no paid tier. Setting your country, board and grade in the short onboarding is optional, but it changes the answer a lot. Without those, the tool teaches the general method correctly and flags where boards differ, instead of guessing at CBSE or Cambridge wording it has no way to verify for you." },
      { q: "Is using this cheating?", a: "Using it to understand something is not cheating. Pasting your homework in, copying the themed answer and handing that in is, and it would read oddly anyway when it is full of cricket. The useful test is simple: could you now explain this to someone with no analogy at all, in the words your syllabus uses? If not, you have not finished yet." },
    ],
  },
};
